services:
  database:
    image: postgres:13
    container_name: bibliotech_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: bibliotech_user
      POSTGRES_PASSWORD: bibliotech_pass
      POSTGRES_DB: bibliotech_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Opcional: PgAdmin para administração do banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bibliotech_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bibliotech.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '8080:80'
    depends_on:
      - database

volumes:
  postgres_data:
